name: cntvkids_app
description: Aplicación móbil para menores.
version: 1.0.1+0
publish_to: none
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  url_launcher: ^5.6.0
  http: ^0.12.2
  html: ^0.14.0+3
  flutter_html: ^0.11.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.9
  loading: ^1.0.2
  intl: ^0.16.1
  share: ^0.6.5
  path_provider: ^1.6.14
  sqflite: ^1.3.1+1
  firebase_messaging: ^7.0.0
  firebase_core: ^0.5.0
  firebase_database: ^4.0.0
  shared_preferences: ^0.5.10
  flutter_widget_from_html: ^0.5.0+3
  cached_network_image: ^2.3.2+1
  provider: ^4.3.2+2
  onesignal_flutter: ^2.6.1
  admob_flutter: ^0.3.4
  firebase_dynamic_links: ^0.6.0
  better_player: ^0.0.49
  flutter_svg: ^0.19.1
  flutter_video_cast: ^1.0.3
  r_dart_library:
    git:
      url: 'https://github.com/YK-Unit/r_dart_library.git'
      ref: 0.2.1
dev_dependencies:
  flutter_native_splash: ^0.2.11  
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/launcher_icon.png
flutter:
  uses-material-design: true
  assets:
  - assets/images/back/back_icon.svg
  - assets/images/backgrounds/18x9/background-red.svg
  - assets/images/backgrounds/background-red.png
  - assets/images/backgrounds/background-red.svg
  - assets/images/chromecast/chromecast_active_icon.png
  - assets/images/chromecast/chromecast_active_icon.svg
  - assets/images/chromecast/chromecast_icon.png
  - assets/images/chromecast/chromecast_icon.svg
  - assets/images/games/games_active_icon.svg
  - assets/images/games/games_badge.svg
  - assets/images/games/games_icon.svg
  - assets/images/lists/lists_active_icon.svg
  - assets/images/lists/lists_badge.svg
  - assets/images/lists/lists_icon.svg
  - assets/images/logo/logo_icon.png
  - assets/images/logo/logo_icon.svg
  - assets/images/record/record_icon.png
  - assets/images/record/record_icon.svg
  - assets/images/search/search_icon.png
  - assets/images/search/search_icon.svg
  - assets/images/series/series_active_icon.svg
  - assets/images/series/series_badge.svg
  - assets/images/series/series_icon.svg
  - assets/images/videos/videos_active_icon.svg
  - assets/images/videos/videos_badge.png
  - assets/images/videos/videos_badge.svg
  - assets/images/videos/videos_icon.svg
  - assets/app/android/icon/drawable-hdpi-icon.png
  - assets/app/android/icon/drawable-ldpi-icon.png
  - assets/app/android/icon/drawable-mdpi-icon.png
  - assets/app/android/icon/drawable-xhdpi-icon.png
  - assets/app/android/icon/drawable-xxhdpi-icon.png
  - assets/app/android/icon/drawable-xxxhdpi-icon.png
  - assets/app/android/icon/icon.png
  - assets/app/android/splash/drawable-land-hdpi-screen.png
  - assets/app/android/splash/drawable-land-ldpi-screen.png
  - assets/app/android/splash/drawable-land-mdpi-screen.png
  - assets/app/android/splash/drawable-land-xhdpi-screen.png
  - assets/app/android/splash/drawable-land-xxhdpi-screen.png
  - assets/app/android/splash/drawable-land-xxxhdpi-screen.png
  - assets/app/android/splash/drawable-port-hdpi-screen.png
  - assets/app/android/splash/drawable-port-ldpi-screen.png
  - assets/app/android/splash/drawable-port-mdpi-screen.png
  - assets/app/android/splash/drawable-port-xhdpi-screen.png
  - assets/app/android/splash/drawable-port-xxhdpi-screen.png
  - assets/app/android/splash/drawable-port-xxxhdpi-screen.png
  - assets/app/android/xml/network_security_config.xml
  - assets/app/icon-android-google-play.png
  - assets/app/icon.png
  - assets/app/ios/icon/icon-1024.png
  - assets/app/ios/icon/icon-108@2x.png
  - assets/app/ios/icon/icon-20.png
  - assets/app/ios/icon/icon-20@2x.png
  - assets/app/ios/icon/icon-20@3x.png
  - assets/app/ios/icon/icon-24@2x.png
  - assets/app/ios/icon/icon-27.5@2x.png
  - assets/app/ios/icon/icon-29.png
  - assets/app/ios/icon/icon-29@2x.png
  - assets/app/ios/icon/icon-29@3x.png
  - assets/app/ios/icon/icon-40.png
  - assets/app/ios/icon/icon-40@2x.png
  - assets/app/ios/icon/icon-40@3x.png
  - assets/app/ios/icon/icon-44@2x.png
  - assets/app/ios/icon/icon-50.png
  - assets/app/ios/icon/icon-50@2x.png
  - assets/app/ios/icon/icon-60.png
  - assets/app/ios/icon/icon-60@2x.png
  - assets/app/ios/icon/icon-60@3x.png
  - assets/app/ios/icon/icon-72.png
  - assets/app/ios/icon/icon-72@2x.png
  - assets/app/ios/icon/icon-76.png
  - assets/app/ios/icon/icon-76@2x.png
  - assets/app/ios/icon/icon-83.5@2x.png
  - assets/app/ios/icon/icon-86@2x.png
  - assets/app/ios/icon/icon-98@2x.png
  - assets/app/ios/icon/icon-small.png
  - assets/app/ios/icon/icon-small@2x.png
  - assets/app/ios/icon/icon-small@3x.png
  - assets/app/ios/icon/icon.png
  - assets/app/ios/icon/icon@2x.png
  - assets/app/ios/splash/Default-2436h.png
  - assets/app/ios/splash/Default-667h.png
  - assets/app/ios/splash/Default-736h.png
  - assets/app/ios/splash/Default-Landscape-2436h.png
  - assets/app/ios/splash/Default-Landscape-736h.png
  - assets/app/preload.gif
  - assets/app/splash.png
  fonts:
  - family: FredokaOne
    fonts:
    - asset: fonts/FredokaOne/FredokaOne.ttf
  - family: Poppins
    fonts:
    - asset: fonts/Poppins/Poppins-Black.ttf
    - asset: fonts/Poppins/Poppins-BlackItalic.ttf
    - asset: fonts/Poppins/Poppins-Bold.ttf
    - asset: fonts/Poppins/Poppins-BoldItalic.ttf
    - asset: fonts/Poppins/Poppins-ExtraBold.ttf
    - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
    - asset: fonts/Poppins/Poppins-ExtraLight.ttf
    - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf
    - asset: fonts/Poppins/Poppins-Italic.ttf
    - asset: fonts/Poppins/Poppins-Light.ttf
    - asset: fonts/Poppins/Poppins-LightItalic.ttf
    - asset: fonts/Poppins/Poppins-Medium.ttf
    - asset: fonts/Poppins/Poppins-MediumItalic.ttf
    - asset: fonts/Poppins/Poppins-Regular.ttf
    - asset: fonts/Poppins/Poppins-SemiBold.ttf
    - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
    - asset: fonts/Poppins/Poppins-Thin.ttf
    - asset: fonts/Poppins/Poppins-ThinItalic.ttf
  - family: Soleil
    fonts:
    - asset: fonts/Soleil/Soleil-Bold-Italic.otf
    - asset: fonts/Soleil/Soleil-Bold.otf
    - asset: fonts/Soleil/Soleil-ExtraBold-Italic.otf
    - asset: fonts/Soleil/Soleil-ExtraBold.otf
    - asset: fonts/Soleil/Soleil-Italic.otf
    - asset: fonts/Soleil/Soleil-Light-Italic.otf
    - asset: fonts/Soleil/Soleil-Light.otf
    - asset: fonts/Soleil/Soleil-Regular.otf
    - asset: fonts/Soleil/Soleil-SemiBold-Italic.otf
    - asset: fonts/Soleil/Soleil-SemiBold.otf

flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  - assets/sounds
  fonts:
  - fonts
flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color is the only required parameter.  It sets the background color of your splash screen.
  color: "#000000"
  
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing 
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a 
  # png file.  
  image: assets/images/logo/logo_icon.png

  # The color_dark and image_dark are parameters that set the color and image when the device is 
  # in dark mode.  If they are not specified, the app will use the color and image above.
  # If the image_dark parameter is specified, color_dark must be specified.
  #color_dark: "#042a49"
  #image_dark: assets/splash-invert.png

  # The android and ios parameters can be used to disable generating a splash screen on a given 
  # platform.
  #android: false
  #ios: false

  # The position of the splash image can be set with android_gravity and ios_content_mode 
  # parameters.  Both default to center.
  #
  # android_gravity can be one of the following Android Gravity (see 
  # https://developer.android.com/reference/android/view/Gravity): bottom, center, 
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see 
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill, 
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight, 
  # bottomLeft, or bottomRight.
  #ios_content_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true
  
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) 
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'