name: cntvkids_app
description: Aplicación móbil para menores.
version: 1.0.1+0
publish_to: none
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  async: ^2.4.2
  audioplayers: ^0.17.3
  better_player: ^0.0.49
  cached_network_image: ^2.3.2+1
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.9
  firebase_core: ^0.5.0
  firebase_database: ^4.0.0
  firebase_dynamic_links: ^0.6.0
  firebase_messaging: ^7.0.0
  flutter:
    sdk: flutter
  flutter_html: ^0.11.0
  flutter_svg: ^0.19.1
  flutter_video_cast: ^1.0.3
  flutter_widget_from_html: ^0.5.0+3
  focus_detector: ^1.1.0+1
  html: ^0.14.0+3
  http: ^0.12.2
  intl: ^0.16.1
  loading:
    git:
      url: 'git://github.com/leonzone/loading.git'
      path: loading
      ref: 8f5a63f
  path_provider: ^1.6.14
  provider: ^4.3.2+2
  r_dart_library:
    git:
      url: 'https://github.com/YK-Unit/r_dart_library.git'
      ref: 0.2.1
  share: ^0.6.5
  shared_preferences: ^0.5.10
  speech_to_text: ^3.1.0
  sqflite: ^1.3.1+1
  url_launcher: ^5.6.0
  webview_flutter: ^1.0.7
  wifi_info_flutter: ^1.0.4
dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.2.11
  flutter_test:
    sdk: flutter
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/app/android/icon/icon.png
flutter:
  uses-material-design: true
  assets:

  # media assets
  - assets/sounds/background/background_1.mp3
  - assets/sounds/background/background_2.mp3
  - assets/sounds/beam/beam.mp3
  - assets/sounds/click/click.mp3
  - assets/sounds/go_back/go_back.mp3
  - assets/sounds/intro/intro.mp3
  - assets/sounds/notification/notification.mp3
  - assets/sounds/wave/wave.mp3
  - assets/sounds/background/background_1.mp4
  - assets/sounds/background/background_2.mp4
  - assets/sounds/beam/beam.mp4
  - assets/sounds/click/click.mp4
  - assets/sounds/go_back/go_back.mp4
  - assets/sounds/intro/intro.mp4
  - assets/sounds/notification/notification.mp4
  - assets/sounds/unavailable_action/unavailable_action.mp4
  - assets/sounds/wave/wave.mp4
  - assets/sounds/click/click.aif
  - assets/sounds/go_back/go_back.aif
  - assets/sounds/notification/notification.aif
  - assets/sounds/results/resultados.aif
  - assets/sounds/unavailable_action/unavailable_action.aif
  - assets/sounds/wave/wave.aif

  # other assets
  - assets/images/back/back_icon.svg
  - assets/images/backgrounds/background-red.svg
  - assets/images/chromecast/chromecast_active_icon.svg
  - assets/images/chromecast/chromecast_icon.svg
  - assets/images/games/games_active_icon.svg
  - assets/images/games/games_badge.svg
  - assets/images/games/games_icon.svg
  - assets/images/lists/lists_active_icon.svg
  - assets/images/lists/lists_badge.svg
  - assets/images/lists/lists_icon.svg
  - assets/images/logo/logo_icon.svg
  - assets/images/player_next/player_next_icon.svg
  - assets/images/player_pause/player_pause_icon.svg
  - assets/images/player_play/player_play_icon.svg
  - assets/images/player_previous/player_previous_icon.svg
  - assets/images/record/record_icon.svg
  - assets/images/search/search_icon.svg
  - assets/images/series/series_active_icon.svg
  - assets/images/series/series_badge.svg
  - assets/images/series/series_icon.svg
  - assets/images/videos/videos_active_icon.svg
  - assets/images/videos/videos_badge.svg
  - assets/images/videos/videos_icon.svg
  - assets/images/backgrounds/18x9/background-red.svg
  - assets/images/chromecast/old/chromecast_active_icon.svg
  - assets/images/chromecast/old/chromecast_icon.svg

  # image assets
  - assets/app/icon-android-google-play.png
  - assets/app/icon.png
  - assets/app/splash.png
  - assets/images/backgrounds/background-red.png
  - assets/images/logo/logo_icon.png
  - assets/images/record/record_icon.png
  - assets/images/search/search_icon.png
  - assets/images/videos/videos_badge.png
  - assets/app/android/icon/drawable-ldpi-icon.png
  - assets/app/android/icon/drawable-xhdpi-icon.png
  - assets/app/android/icon/drawable-xxxhdpi-icon.png
  - assets/app/ios/icon/icon-1024.png
  - assets/app/ios/icon/icon-20.png
  - assets/app/ios/icon/icon-20@3x.png
  - assets/app/ios/icon/icon-27.5@2x.png
  - assets/app/ios/icon/icon-29@2x.png
  - assets/app/ios/icon/icon-40.png
  - assets/app/ios/icon/icon-40@3x.png
  - assets/app/ios/icon/icon-50.png
  - assets/app/ios/icon/icon-60.png
  - assets/app/ios/icon/icon-60@3x.png
  - assets/app/ios/icon/icon-72@2x.png
  - assets/app/ios/icon/icon-76@2x.png
  - assets/app/ios/icon/icon-86@2x.png
  - assets/app/ios/icon/icon-small.png
  - assets/app/ios/icon/icon-small@3x.png
  - assets/app/ios/icon/icon@2x.png
  - assets/images/chromecast/old/chromecast_active_icon.png
  - assets/images/chromecast/old/chromecast_icon.png
  - assets/images/record/2.0x/record_icon.png
  - assets/images/search/2.0x/search_icon.png
  - assets/app/preload.gif

  # font assets:
  fonts:
  - family: FredokaOne
    fonts:
    - asset: fonts/FredokaOne/FredokaOne.ttf
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  - assets/sounds
  fonts:
  - fonts
flutter_native_splash:
  color: '#FFFFFF'
  image: assets/images/logo/logo_icon.png
