// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: cntvkids_app
  static const package = "cntvkids_app";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName})
      : assert(assetName != null);

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/backgrounds/background-red.png
  // ignore: non_constant_identifier_names
  final background_red = const AssetResource(
      "assets/images/backgrounds/background-red.png",
      packageName: null);

  /// asset: assets/images/chromecast/chromecast_active_icon.png
  // ignore: non_constant_identifier_names
  final chromecast_active_icon = const AssetResource(
      "assets/images/chromecast/chromecast_active_icon.png",
      packageName: null);

  /// asset: assets/images/chromecast/chromecast_icon.png
  // ignore: non_constant_identifier_names
  final chromecast_icon = const AssetResource(
      "assets/images/chromecast/chromecast_icon.png",
      packageName: null);

  /// asset: assets/images/logo/logo_icon.png
  // ignore: non_constant_identifier_names
  final logo_icon = const AssetResource("assets/images/logo/logo_icon.png",
      packageName: null);

  /// asset: assets/images/record/record_icon.png
  // ignore: non_constant_identifier_names
  final record_icon = const AssetResource(
      "assets/images/record/record_icon.png",
      packageName: null);

  /// asset: assets/images/search/search_icon.png
  // ignore: non_constant_identifier_names
  final search_icon = const AssetResource(
      "assets/images/search/search_icon.png",
      packageName: null);

  /// asset: assets/images/videos/videos_badge.png
  // ignore: non_constant_identifier_names
  final videos_badge = const AssetResource(
      "assets/images/videos/videos_badge.png",
      packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

  /// asset: assets/images/back/back_icon.svg
  // ignore: non_constant_identifier_names
  final back_icon = const AssetResource("assets/images/back/back_icon.svg",
      packageName: null);

  /// asset: assets/images/backgrounds/18x9/background-red.svg
  // ignore: non_constant_identifier_names
  final background_red = const AssetResource(
      "assets/images/backgrounds/18x9/background-red.svg",
      packageName: null);

  /// asset: assets/images/backgrounds/background-red.svg
  // ignore: non_constant_identifier_names
  final background_red$1 = const AssetResource(
      "assets/images/backgrounds/background-red.svg",
      packageName: null);

  /// asset: assets/images/chromecast/chromecast_active_icon.svg
  // ignore: non_constant_identifier_names
  final chromecast_active_icon = const AssetResource(
      "assets/images/chromecast/chromecast_active_icon.svg",
      packageName: null);

  /// asset: assets/images/chromecast/chromecast_icon.svg
  // ignore: non_constant_identifier_names
  final chromecast_icon = const AssetResource(
      "assets/images/chromecast/chromecast_icon.svg",
      packageName: null);

  /// asset: assets/images/games/games_active_icon.svg
  // ignore: non_constant_identifier_names
  final games_active_icon = const AssetResource(
      "assets/images/games/games_active_icon.svg",
      packageName: null);

  /// asset: assets/images/games/games_badge.svg
  // ignore: non_constant_identifier_names
  final games_badge = const AssetResource("assets/images/games/games_badge.svg",
      packageName: null);

  /// asset: assets/images/games/games_icon.svg
  // ignore: non_constant_identifier_names
  final games_icon = const AssetResource("assets/images/games/games_icon.svg",
      packageName: null);

  /// asset: assets/images/lists/lists_active_icon.svg
  // ignore: non_constant_identifier_names
  final lists_active_icon = const AssetResource(
      "assets/images/lists/lists_active_icon.svg",
      packageName: null);

  /// asset: assets/images/lists/lists_badge.svg
  // ignore: non_constant_identifier_names
  final lists_badge = const AssetResource("assets/images/lists/lists_badge.svg",
      packageName: null);

  /// asset: assets/images/lists/lists_icon.svg
  // ignore: non_constant_identifier_names
  final lists_icon = const AssetResource("assets/images/lists/lists_icon.svg",
      packageName: null);

  /// asset: assets/images/logo/logo_icon.svg
  // ignore: non_constant_identifier_names
  final logo_icon = const AssetResource("assets/images/logo/logo_icon.svg",
      packageName: null);

  /// asset: assets/images/record/record_icon.svg
  // ignore: non_constant_identifier_names
  final record_icon = const AssetResource(
      "assets/images/record/record_icon.svg",
      packageName: null);

  /// asset: assets/images/search/search_icon.svg
  // ignore: non_constant_identifier_names
  final search_icon = const AssetResource(
      "assets/images/search/search_icon.svg",
      packageName: null);

  /// asset: assets/images/series/series_active_icon.svg
  // ignore: non_constant_identifier_names
  final series_active_icon = const AssetResource(
      "assets/images/series/series_active_icon.svg",
      packageName: null);

  /// asset: assets/images/series/series_badge.svg
  // ignore: non_constant_identifier_names
  final series_badge = const AssetResource(
      "assets/images/series/series_badge.svg",
      packageName: null);

  /// asset: assets/images/series/series_icon.svg
  // ignore: non_constant_identifier_names
  final series_icon = const AssetResource(
      "assets/images/series/series_icon.svg",
      packageName: null);

  /// asset: assets/images/videos/videos_active_icon.svg
  // ignore: non_constant_identifier_names
  final videos_active_icon = const AssetResource(
      "assets/images/videos/videos_active_icon.svg",
      packageName: null);

  /// asset: assets/images/videos/videos_badge.svg
  // ignore: non_constant_identifier_names
  final videos_badge = const AssetResource(
      "assets/images/videos/videos_badge.svg",
      packageName: null);

  /// asset: assets/images/videos/videos_icon.svg
  // ignore: non_constant_identifier_names
  final videos_icon = const AssetResource(
      "assets/images/videos/videos_icon.svg",
      packageName: null);
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/backgrounds/background-red.png
  // ignore: non_constant_identifier_names
  AssetImage background_red() {
    return AssetImage(asset.background_red.keyName);
  }

  /// asset: assets/images/chromecast/chromecast_active_icon.png
  // ignore: non_constant_identifier_names
  AssetImage chromecast_active_icon() {
    return AssetImage(asset.chromecast_active_icon.keyName);
  }

  /// asset: assets/images/chromecast/chromecast_icon.png
  // ignore: non_constant_identifier_names
  AssetImage chromecast_icon() {
    return AssetImage(asset.chromecast_icon.keyName);
  }

  /// asset: assets/images/logo/logo_icon.png
  // ignore: non_constant_identifier_names
  AssetImage logo_icon() {
    return AssetImage(asset.logo_icon.keyName);
  }

  /// asset: assets/images/record/record_icon.png
  // ignore: non_constant_identifier_names
  AssetImage record_icon() {
    return AssetImage(asset.record_icon.keyName);
  }

  /// asset: assets/images/search/search_icon.png
  // ignore: non_constant_identifier_names
  AssetImage search_icon() {
    return AssetImage(asset.search_icon.keyName);
  }

  /// asset: assets/images/videos/videos_badge.png
  // ignore: non_constant_identifier_names
  AssetImage videos_badge() {
    return AssetImage(asset.videos_badge.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

  /// asset: assets/images/back/back_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg back_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.back_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/backgrounds/18x9/background-red.svg
  // ignore: non_constant_identifier_names
  AssetSvg background_red({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.background_red.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/backgrounds/background-red.svg
  // ignore: non_constant_identifier_names
  AssetSvg background_red$1({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.background_red$1.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/chromecast/chromecast_active_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg chromecast_active_icon(
      {@required double width, @required double height}) {
    final imageProvider = AssetSvg(asset.chromecast_active_icon.keyName,
        width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/chromecast/chromecast_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg chromecast_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.chromecast_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/games/games_active_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg games_active_icon(
      {@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.games_active_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/games/games_badge.svg
  // ignore: non_constant_identifier_names
  AssetSvg games_badge({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.games_badge.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/games/games_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg games_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.games_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/lists/lists_active_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg lists_active_icon(
      {@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.lists_active_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/lists/lists_badge.svg
  // ignore: non_constant_identifier_names
  AssetSvg lists_badge({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.lists_badge.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/lists/lists_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg lists_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.lists_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/logo/logo_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg logo_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.logo_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/record/record_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg record_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.record_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/search/search_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg search_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.search_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/series/series_active_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg series_active_icon(
      {@required double width, @required double height}) {
    final imageProvider = AssetSvg(asset.series_active_icon.keyName,
        width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/series/series_badge.svg
  // ignore: non_constant_identifier_names
  AssetSvg series_badge({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.series_badge.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/series/series_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg series_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.series_icon.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/videos/videos_active_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg videos_active_icon(
      {@required double width, @required double height}) {
    final imageProvider = AssetSvg(asset.videos_active_icon.keyName,
        width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/videos/videos_badge.svg
  // ignore: non_constant_identifier_names
  AssetSvg videos_badge({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.videos_badge.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: assets/images/videos/videos_icon.svg
  // ignore: non_constant_identifier_names
  AssetSvg videos_icon({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.videos_icon.keyName, width: width, height: height);
    return imageProvider;
  }
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();

  /// font family: FredokaOne
  // ignore: non_constant_identifier_names
  final fredokaOne = "FredokaOne";

  /// font family: Poppins
  // ignore: non_constant_identifier_names
  final poppins = "Poppins";

  /// font family: Soleil
  // ignore: non_constant_identifier_names
  final soleil = "Soleil";
}
